// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flash_chat_flutter/secrets.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webOptions,
    appId: '1:195560521523:web:5796f1499756ddfd35c846',
    messagingSenderId: '195560521523',
    projectId: 'flash-chat-54772',
    authDomain: 'flash-chat-54772.firebaseapp.com',
    storageBucket: 'flash-chat-54772.appspot.com',
    measurementId: 'G-C0Y6TR8MQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidOptions,
    appId: '1:195560521523:android:5ebd781a06e85b7135c846',
    messagingSenderId: '195560521523',
    projectId: 'flash-chat-54772',
    storageBucket: 'flash-chat-54772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iosOptions,
    appId: '1:195560521523:ios:48816abb4e0946e035c846',
    messagingSenderId: '195560521523',
    projectId: 'flash-chat-54772',
    storageBucket: 'flash-chat-54772.appspot.com',
    iosClientId:
        '195560521523-3va38bg7r2f638lur7r4gbsod053nhr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: macosOptions,
    appId: '1:195560521523:ios:48816abb4e0946e035c846',
    messagingSenderId: '195560521523',
    projectId: 'flash-chat-54772',
    storageBucket: 'flash-chat-54772.appspot.com',
    iosClientId:
        '195560521523-3va38bg7r2f638lur7r4gbsod053nhr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );
}
